function [vth] = convertVth(MSB_vth, LSB_vth)

    % The bottom one is more accurate (tolerates misread MSB_vth values)
%     vth = 50 + LSB_vth + (LSB_vth == 0) .* (MSB_vth - 50) ...
%         + ((LSB_vth > 0) & (LSB_vth <= 64)) .* (round((MSB_vth - LSB_vth)/2) - 25) ...
%         + ((LSB_vth > 64) & (LSB_vth < 128)) .* (90 - round((MSB_vth + LSB_vth)/2)) ...
%         + (LSB_vth == 128) .* (52 - MSB_vth);
    vth = 50 + LSB_vth + (LSB_vth == 0) .* (MSB_vth - 50) ...
        + ((LSB_vth > 0) & (LSB_vth <= 38)) .* (round((MSB_vth - LSB_vth)/2) - 25) ...
        + ((LSB_vth > 88) & (LSB_vth < 128)) .* (90 - round((MSB_vth + LSB_vth)/2)) ...
        + (LSB_vth == 128) .* (52 - MSB_vth);

end