function [vth] = convertVth(MSB_vth, CSB_vth, LSB_vth)

    % double check this -- right now is copied from toshiba 19nm tlc
    vth = uint16(...
            (CSB_vth <= 0) .* (LSB_vth) + ...
            (CSB_vth > 0 & CSB_vth <= 100) .* round( (CSB_vth + LSB_vth + 62) / 2 ) + ...
            (CSB_vth > 100 & CSB_vth <= 128) .* ( 116 + MSB_vth ) + ...
            (CSB_vth > 128 & CSB_vth <= 160) .* ( 492 - LSB_vth ) + ...
            (CSB_vth > 160 & CSB_vth < 256) .* round( (CSB_vth - MSB_vth + 918) / 2 ) + ...
            (CSB_vth >= 256) .* ( 612 - MSB_vth ) ...
          );

end