function [vth] = convertVth(MSB_vth, CSB_vth, LSB_vth)

    % The bottom one is more accurate (tolerates misread MSB_vth values)
    vth = uint16(...
            (CSB_vth <= 0) .* (LSB_vth) + ...
            (CSB_vth > 0 & CSB_vth <= 100) .* round( (CSB_vth + LSB_vth + 62) / 2 ) + ...
            (CSB_vth > 100 & CSB_vth <= 128) .* ( 124 + MSB_vth ) + ...
            (CSB_vth > 128 & CSB_vth <= 160) .* ( 500 - LSB_vth ) + ...
            (CSB_vth > 160 & CSB_vth < 256) .* round( (CSB_vth - MSB_vth + 934) / 2 ) + ...
            (CSB_vth >= 256) .* ( 628 - MSB_vth ) ...
          );

end